name: build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
    - name: Install dotnet ef
      run: dotnet tool install --global dotnet-ef
    - name: Build with dotnet
      run: dotnet build --configuration Release HomiePages.sln
    - name: Push to Linode
        run: |
          echo "$ssh_key" > ~/ssh_key
          chmod 600 ~/ssh_key
          rsync -e "ssh -i ~/ssh_key -o StrictHostKeyChecking=no" -avzr .src/WebUI/bin/Release/net5.0/publish/ "$user"@"$target_ip":/var/homiepages/app
        env:
          ssh_key: ${{ secrets.CICD_SSH }}
          user: ${{ secrets.CICD_USER }}
          target_ip: ${{ secrets.LINODE_IP }}